import { AuthProvider } from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header classname="header">
  <div className="header-container">
      <button className="btn btn-primary">
        <Link href="/">Home</Link>
        </button>    
    <button className="btn btn-primary">
      <Link href="/login">Login</Link>
    </button>
    <button className="btn btn-primary">
      <Link href="/register">Register</Link>
    </button>
  </div>
</header>

        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}


